# Generated by Django 5.1.2 on 2025-03-18 09:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_upload_to, validators=[accounts.models.validate_image_extension], verbose_name='프로필 사진'),
        ),
    ]
